-- PhishGuard Prize Demo
-- Safe setup: stores the participant name only.
-- The demo password is NEVER stored.

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null
);

alter table public.profiles enable row level security;

drop policy if exists "Allow demo name inserts" on public.profiles;

create policy "Allow demo name inserts"
on public.profiles
for insert
to anon, authenticated
with check (length(trim(name)) > 0);

drop policy if exists "Allow demo name reads" on public.profiles;

create policy "Allow demo name reads"
on public.profiles
for select
to anon, authenticated
using (true);
